# Generated by Django 3.0.2 on 2020-02-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_articles', models.IntegerField(default=0)),
                ('rss_feed', models.CharField(default='default', max_length=200)),
                ('picture', models.CharField(default='default', max_length=200)),
                ('abbreviation', models.CharField(default='default', max_length=200)),
                ('website', models.CharField(default='default', max_length=200)),
                ('funding', models.CharField(default='default', max_length=200)),
                ('sponsor', models.CharField(default='default', max_length=200)),
                ('number_authors', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='number_articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='social_media',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='work_history',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
