# Generated by Django 3.0.2 on 2020-02-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200201_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(default='default', max_length=200)),
                ('publisher', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
