# Generated by Django 3.0.2 on 2020-03-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookmark_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrss',
            name='feed_added',
            field=models.BooleanField(default=False),
        ),
    ]
