# Generated by Django 3.0.2 on 2020-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200203_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='number_articles',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='sponsor',
        ),
        migrations.AlterField(
            model_name='author',
            name='articles',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_media',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='work_history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abbreviation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='funding',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='picture',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='rss_feed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
