# Generated by Django 3.0.2 on 2020-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200204_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('rss_feed', models.CharField(default='', max_length=200)),
                ('picture', models.CharField(default='', max_length=200)),
                ('abbreviation', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('funding', models.CharField(default='', max_length=200)),
                ('number_authors', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
    ]
