# Generated by Django 3.0.2 on 2020-03-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200312_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='feed_removed',
            field=models.BooleanField(default=True),
        ),
    ]
