# Generated by Django 3.0.2 on 2020-02-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='magnitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
