# Generated by Django 3.0.2 on 2020-02-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
