# Generated by Django 3.0.2 on 2020-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200209_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
