# Generated by Django 3.0.2 on 2020-02-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200209_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Entity')),
                ('key', models.CharField(default='', max_length=200)),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
