# Generated by Django 3.0.2 on 2020-02-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_entitymanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityManager',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='salience',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='wiki',
        ),
    ]
