# Generated by Django 3.0.2 on 2020-02-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200209_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
    ]
