# Generated by Django 3.0.2 on 2020-02-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200209_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='mid',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='salience',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='wiki',
            field=models.URLField(default='', null=True),
        ),
    ]
