# Generated by Django 3.0.2 on 2020-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200209_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='author',
            name='work_history',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='number_authors',
        ),
    ]
