# Generated by Django 3.0.2 on 2020-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200209_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
