# Generated by Django 3.0.2 on 2020-02-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_entity_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
