# Generated by Django 3.0.2 on 2020-02-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200217_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Entity')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('url', models.URLField(default='')),
                ('article_body', models.TextField()),
            ],
        ),
    ]
